// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARMfC1-XPh1vHGKqdgAMWR3R_LxGCcnwA',
    appId: '1:484684712012:web:1db4aec9a76b47e9090ce9',
    messagingSenderId: '484684712012',
    projectId: 'internshiptask-8c7de',
    authDomain: 'internshiptask-8c7de.firebaseapp.com',
    storageBucket: 'internshiptask-8c7de.firebasestorage.app',
    measurementId: 'G-CM8SX28P98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1O6C6dNtxbOzrog-B-9o36GoF3STsQ2c',
    appId: '1:484684712012:android:43823ea726752683090ce9',
    messagingSenderId: '484684712012',
    projectId: 'internshiptask-8c7de',
    storageBucket: 'internshiptask-8c7de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBGGgl-BN_g2Mg6KpNi8LrmfoBjDTC6II',
    appId: '1:484684712012:ios:e84998eaf1851589090ce9',
    messagingSenderId: '484684712012',
    projectId: 'internshiptask-8c7de',
    storageBucket: 'internshiptask-8c7de.firebasestorage.app',
    iosBundleId: 'com.example.internshipTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBGGgl-BN_g2Mg6KpNi8LrmfoBjDTC6II',
    appId: '1:484684712012:ios:e84998eaf1851589090ce9',
    messagingSenderId: '484684712012',
    projectId: 'internshiptask-8c7de',
    storageBucket: 'internshiptask-8c7de.firebasestorage.app',
    iosBundleId: 'com.example.internshipTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARMfC1-XPh1vHGKqdgAMWR3R_LxGCcnwA',
    appId: '1:484684712012:web:c1be5fb81f397f29090ce9',
    messagingSenderId: '484684712012',
    projectId: 'internshiptask-8c7de',
    authDomain: 'internshiptask-8c7de.firebaseapp.com',
    storageBucket: 'internshiptask-8c7de.firebasestorage.app',
    measurementId: 'G-T9WL2RP4WR',
  );

}